### ISSUE TITLE
Oppdaterer ikke lenger i YT Music?

### ISSUE THREAD

**Issue by dhmyrdal** [sindrel/nrk-pod-feeds#124]
Har brukt feed i YT Music i noen måneder, men alle feedene stoppet fra ca 19.oktober i år?
Det er det samme om jet sletter / legger til. restarter ser på en "ny" feed jeg ikke har brukt - synlige episoder i 10 siste fra xxx stopper midt i oktober.

Jeg har en mistanke om at det er på YT sin side, for feeden ser normal ut når jeg ser på tekst output.

Kjører yt Music i familie versjon på en Google Pixel 7 pro

takk for en fantastisk service så langt!

**Comment by sindrel** [comment]
Hei, @dhmyrdal! Jeg har lite erfaring med YT Music, men hvis feedene har fått nytt innhold har du nok rett i at det må være et eller annet de har gjort på sin side. Ukjent hva eller hvorfor, men bra å være oppmerksom på. Takk!

**Comment by dhmyrdal** [comment]
Prøvde samme i pocket cast, hvor samme feeds virker. Er antagelig noe Google har funnet på da.
