### ISSUE TITLE
I det lange løp disabled 

### ISSUE THREAD

**Issue by hernil** [sindrel/nrk-pod-feeds#37]
Hi! 

I noticed that 2c47931e5a08e912659e5e023555cc48c7c0c42d disabled "I det lange Løp". Was this an intended change or just a slip up in a larger refactor? :blush:

**Comment by sindrel** [comment]
Hi @hernil!

You're right, seems it was accidentally caught up in a refactor. :grimacing: Should be fixed now, the latest episodes should start showing up soon.

Thanks for noticing!
